---
- name: Include OS specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: nstall MongoDB
  include_tasks: install.yml

- name: Configure MongoDB
  include_tasks: config.yml

- name: Start MongoDB service
  include_tasks: service.yml
