---
mongodb_package: mongodb-org
mongodb_service: mongod

mongodb_repo: "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/7.0 multiverse"
mongodb_gpg_key: "https://pgp.mongodb.com/server-7.0.asc"
